name: Stryker.NET Mutation Testing

on:
  pull_request:
    branches: [main]

jobs:
  mutation-testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
      
    - name: Install dotnet tools
      working-directory: TestYourTest
      run: dotnet tool restore
    
    - name: Run Stryker.NET
      working-directory: TestYourTest/UnitTests
      run: dotnet stryker --reporter "markdown"

    - name: Find Markdown files recursively
      id: find-md-files
      run: |
        md_files=$(find ./TestYourTest/UnitTests -name "*.md")
        echo "::set-output name=md_files::${md_files}"

    - name: Post Stryker report as comment
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const path = require('path');

          const mdFiles = "${{ steps.find-md-files.outputs.md_files }}".split("\n");

          let reportContent = "";
          mdFiles.forEach(file => {
            reportContent += fs.readFileSync(file, 'utf8') + '\n';
          });
          
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: reportContent
          });
